name: pogema-appo-multiple-configs-autocurriculum

global_settings:
  use_wandb: True
experiment_settings:
  save_every_sec: 120
  encoder_custom: pogema_residual
  train_for_env_steps: 1000000000
async_ppo:
  experiment_summaries_interval: 5
  ppo_epochs: 1
  batch_size: 4096
  use_rnn: True
  max_grad_norm: 0.0
  num_workers: 6
  num_envs_per_worker: 6
  with_pbt: False
environment:
  name: Pogema-v0
  framestack: 1
  max_episode_steps: 256
  path_to_grid_configs: training_configs/train_maps
  grid_config:
    num_agents: 64
    density: 0.3
    size: 20